### ISSUE TITLE
alpino.bash on macOS and BSD

### ISSUE THREAD

**Issue by danieldk** [rug-compling/alpino-docker#1]
It's great that you wrote a Dockerfile for Alpino. The `alpino.bash` script works great on macOS when the whole NFS check is wrapped in a

```
if [ $(uname -s) = "Linux" ]; then
#...
fi
```

(macOS and BSD's `stat` have different flags than Linux and no obvious method to get the filesystem type.)

**Comment by pebbe** [comment]
Fixed
